from __future__ import annotations

import os
import sqlite3
import tempfile
from collections.abc import Collection
from contextlib import closing
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator
from ruamel.yaml import YAML
from ruamel.yaml.error import YAMLError

from seriemacv.styles import ResumeStyleId

CONFIG_FILE = "seriemacv.yml"
PROJECT_DIRECTORIES = (
    "career.locales",
    "i18n",
    "resume",
    "resume/variants",
    "jobs",
    "jobs/sources",
    "applications",
    "styles",
    "exports",
    ".seriemacv/cache",
    ".seriemacv/browser",
    ".seriemacv/index",
)
LEGACY_PROJECT_DIRECTORIES = (
    "resume",
    "resume/variants",
    "jobs",
    "jobs/sources",
    "applications",
    "knowledge",
    "styles",
    "exports",
    ".seriemacv/cache",
    ".seriemacv/browser",
    ".seriemacv/index",
)
PROJECT_ARTIFACTS = {
    "career.yml": (
        "# Canonical, user-owned career data\n"
        "schema_version: 2\n"
        "profile:\n"
        '  name: ""\n'
        '  email: ""\n'
        '  linkedin: ""\n'
        '  portfolio: ""\n'
        "experience: []\n"
        "education: []\n"
        "skills: []\n"
        "evidence: []\n"
        "answers: []\n"
        "stories: []\n"
    ),
    "career.locales/pt-BR.yml": (
        "schema_version: 1\nlocale: pt-BR\nprofile: {title: '', location: ''}\n"
        "summary: ''\nexperience: {}\neducation: {}\nskills: {}\n"
    ),
    "career.locales/en.yml": (
        "schema_version: 1\nlocale: en\nprofile: {title: '', location: ''}\n"
        "summary: ''\nexperience: {}\neducation: {}\nskills: {}\n"
    ),
    "i18n/pt-BR.yml": (
        "schema_version: 1\nlocale: pt-BR\n"
        "labels: {summary: Resumo, experience: Experiência profissional, education: Formação acadêmica, skills: Habilidades, languages: Idiomas, current: Atual, other: Outras, level.beginner: Iniciante, level.intermediate: Intermediário, level.advanced: Avançado, level.expert: Especialista}\n"
        "months: [Jan., Fev., Mar., Abr., Mai., Jun., Jul., Ago., Set., Out., Nov., Dez.]\n"
        "date_format: '{month} de {year}'\n"
    ),
    "i18n/en.yml": (
        "schema_version: 1\nlocale: en\n"
        "labels: {summary: Summary, experience: Professional Experience, education: Education, skills: Skills, languages: Languages, current: Present, other: Other, level.beginner: Beginner, level.intermediate: Intermediate, level.advanced: Advanced, level.expert: Expert}\n"
        "months: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]\n"
        "date_format: '{month} {year}'\n"
    ),
}
LEGACY_PROJECT_ARTIFACTS = (
    "profile.yml",
    "resume/master.md",
    "knowledge/achievements.yml",
    "knowledge/skills.yml",
    "knowledge/answers.md",
    "knowledge/stories.md",
)
PROJECT_EXAMPLES = {
    "career.yml.example": (
        "# Fictitious example. Replace it with facts you have verified.\n"
        "schema_version: 2\n"
        "profile:\n"
        "  name: Seriema Example\n"
        "  email: seriema@example.invalid\n"
        "  phone: '+55 11 5555-0100'\n"
        "  links:\n"
        "    github: https://github.com/seriema-example\n"
        "experience:\n"
        "  - id: example-platform\n"
        "    company: Example Systems\n"
        "    start_date: 2024-01\n"
        "education:\n"
        "  - id: example-degree\n"
        "    institution: Example University\n"
        "    start_date: 2018-01\n"
        "    end_date: 2021-12\n"
        "skills:\n"
        "  - id: python\n"
        "evidence:\n"
        "  - id: example-service\n"
        "    experience_id: example-platform\n"
        "    statement: Delivered a documented internal service.\n"
        "    tags: [python, documentation]\n"
        "    details: [Reviewed service requirements with the team.]\n"
        "    verified: true\n"
        "answers:\n"
        "  - id: work-authorization\n"
        "    prompt: Are you authorized to work in Brazil?\n"
        "    answer: Yes.\n"
        "stories:\n"
        "  - id: example-delivery\n"
        "    title: Service delivery\n"
        "    situation: A team needed a documented internal service.\n"
        "    action: Collaborated on delivery and documentation.\n"
        "    result: Service released for internal use.\n"
        "    evidence_ids: [example-service]\n"
    ),
    "seriemacv.yml.example": (
        "# Example project configuration. This file contains no secrets.\n"
        "schema_version: 2\n"
        'project_name: "Example Career"\n'
        "resume_language: pt-BR\n"
        "resume_style: clean\n"
        'resume_color: "#647D74"\n'
    ),
    "job.yml.example": (
        "# Fictitious example. A structured proposal may be generated by an AI.\n"
        "schema_version: 1\n"
        "id: example-platform-engineer\n"
        "title: Platform Engineer\n"
        "description: Build and operate reliable cloud-platform services.\n"
        "company: Example Systems\n"
        "location: Example City, Brazil\n"
        "work_model: Remote\n"
        "employment_type: Full-time\n"
        "seniority: Senior\n"
        "language: English\n"
        "salary_range: 'USD 120,000-150,000 annually'\n"
        "requirements:\n"
        "  - id: python\n"
        "    statement: Professional Python experience.\n"
        "    priority: required\n"
        "  - id: cloud\n"
        "    statement: Cloud-platform experience.\n"
        "    priority: preferred\n"
    ),
    "variant.yml.example": (
        "# Fictitious resume variant. Every id must reference canonical data.\n"
        "schema_version: 1\n"
        "id: example-platform-variant\n"
        "job_id: example-platform-engineer\n"
        "style: clean\n"
        "selection:\n"
        "  experience: [example-platform]\n"
        "  education: [example-degree]\n"
        "  skills: [python]\n"
    ),
    "variant-locale.yml.example": (
        "# Partial job-specific overrides; omitted content inherits the career locale.\n"
        "schema_version: 1\n"
        "locale: en\n"
        "evidence_ids: [example-service]\n"
        "profile:\n"
        "  title: Platform Engineer\n"
        "summary: Builds reliable platform services with collaborative teams.\n"
        "experience:\n"
        "  example-platform:\n"
        "    highlights: [Delivered a documented internal service.]\n"
    ),
    "career.locales/pt-BR.yml.example": (
        "schema_version: 1\nlocale: pt-BR\nprofile: {title: Engenheiro de Software, location: 'Cidade Exemplo, Brasil', languages: [Português, Inglês]}\nsummary: Desenvolve software confiável com equipes colaborativas.\nexperience: {example-platform: {title: Engenheiro de Software, highlights: [Entregou um serviço interno documentado.]}}\neducation: {example-degree: {degree: Bacharelado em Tecnologia}}\nskills: {python: {name: Python, category: Linguagem de programação}}\n"
    ),
    "career.locales/en.yml.example": (
        "schema_version: 1\nlocale: en\nprofile: {title: Software Engineer, location: 'Example City, Brazil', languages: [Portuguese, English]}\nsummary: Build reliable software with collaborative teams.\nexperience: {example-platform: {title: Software Engineer, highlights: [Delivered a documented internal service.]}}\neducation: {example-degree: {degree: Bachelor of Technology}}\nskills: {python: {name: Python, category: Programming language}}\n"
    ),
    "i18n/pt-BR.yml.example": (
        "schema_version: 1\nlocale: pt-BR\n"
        "labels: {summary: Resumo, experience: Experiência profissional, education: Formação acadêmica, skills: Habilidades, languages: Idiomas, current: Atual, other: Outras, level.beginner: Iniciante, level.intermediate: Intermediário, level.advanced: Avançado, level.expert: Especialista}\n"
        "months: [Jan., Fev., Mar., Abr., Mai., Jun., Jul., Ago., Set., Out., Nov., Dez.]\n"
        "date_format: '{month} de {year}'\n"
    ),
    "i18n/en.yml.example": (
        "schema_version: 1\nlocale: en\n"
        "labels: {summary: Summary, experience: Professional Experience, education: Education, skills: Skills, languages: Languages, current: Present, other: Other, level.beginner: Beginner, level.intermediate: Intermediate, level.advanced: Advanced, level.expert: Expert}\n"
        "months: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]\n"
        "date_format: '{month} {year}'\n"
    ),
}
DATABASE_RELATIVE_PATH = Path(".seriemacv/index/seriemacv.db")


class ProjectAlreadyExistsError(FileExistsError):
    """Raised when creating a project would overwrite its configuration."""


class InvalidProjectError(ValueError):
    """Raised when a directory does not satisfy the seriemaCV project contract."""


@dataclass(frozen=True)
class CareerProject:
    """Validated local project and its private SQLite index."""

    path: Path
    name: str
    resume_language: str
    resume_style: ResumeStyleId
    database_path: Path
    database_schema_version: int


class ProjectConfiguration(BaseModel):
    """Strict, versioned configuration owned by a career project."""

    model_config = ConfigDict(extra="forbid", strict=True)

    schema_version: Literal[2]
    project_name: str = Field(min_length=1, max_length=120)
    resume_language: str = "pt-BR"
    resume_style: ResumeStyleId = "clean"
    resume_color: str = "647D74"

    @field_validator("project_name")
    @classmethod
    def project_name_cannot_be_blank(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("must not be blank")
        return value

    @field_validator("resume_language")
    @classmethod
    def resume_language_is_locale(cls, value: str) -> str:
        import re
        if not re.fullmatch(r"[A-Za-z]{2,8}(?:-[A-Za-z0-9]{2,8})*", value):
            raise ValueError("must be a BCP 47 locale identifier")
        return value

    @field_validator("resume_color")
    @classmethod
    def resume_color_is_hexadecimal(cls, value: str) -> str:
        import re

        normalized = value.removeprefix("#")
        if not re.fullmatch(r"[0-9A-Fa-f]{6}", normalized):
            raise ValueError("must be a six-digit hexadecimal RGB color")
        return normalized.upper()


def create_project(
    path: Path,
    *,
    project_name: str,
    resume_language: str = "pt-BR",
    resume_style: ResumeStyleId = "clean",
) -> Path:
    """Create a new portable seriemaCV project without overwriting one."""
    project_path = path.expanduser().resolve()
    ProjectConfiguration(
        schema_version=2,
        project_name=project_name,
        resume_language=resume_language,
        resume_style=resume_style,
    )

    if (project_path / CONFIG_FILE).exists():
        raise ProjectAlreadyExistsError(
            f"A seriemaCV project already exists at {project_path}"
        )

    project_path.mkdir(parents=True, exist_ok=True)
    for relative_directory in PROJECT_DIRECTORIES:
        (project_path / relative_directory).mkdir(parents=True, exist_ok=True)
    for relative_path, content in PROJECT_ARTIFACTS.items():
        (project_path / relative_path).parent.mkdir(parents=True, exist_ok=True)
        _atomic_write(project_path / relative_path, content)
    for relative_path, content in PROJECT_EXAMPLES.items():
        (project_path / relative_path).parent.mkdir(parents=True, exist_ok=True)
        _atomic_write(project_path / relative_path, content)

    config = (
        "# seriemaCV project configuration\n"
        "schema_version: 2\n"
        f"project_name: {_yaml_string(project_name)}\n"
        f"resume_language: {resume_language}\n"
        f"resume_style: {resume_style}\n"
        'resume_color: "#647D74"\n'
    )
    _atomic_write(project_path / CONFIG_FILE, config)
    _initialize_database(project_path / DATABASE_RELATIVE_PATH)
    return project_path


def load_template(
    path: Path,
    template_name: Literal["career", "job", "variant", "variant-locale"],
) -> str:
    """Read a local example, falling back to the built-in template for older projects."""
    filename = f"{template_name}.yml.example"
    template_path = path.expanduser().resolve() / filename
    if template_path.is_file():
        return template_path.read_text(encoding="utf-8")
    return PROJECT_EXAMPLES[filename]


def open_project(path: Path) -> CareerProject:
    """Open a validated project and return its local infrastructure paths."""
    project_path = path.expanduser().resolve()
    errors = validate_project(project_path)
    if errors:
        raise InvalidProjectError("; ".join(errors))

    configuration = _read_project_configuration(project_path / CONFIG_FILE)
    database_path = project_path / DATABASE_RELATIVE_PATH
    return CareerProject(
        path=project_path,
        name=configuration.project_name,
        resume_language=configuration.resume_language,
        resume_style=configuration.resume_style,
        database_path=database_path,
        database_schema_version=_database_schema_version(database_path),
    )


def validate_project(path: Path) -> list[str]:
    """Return validation errors for a project; an empty list means valid."""
    project_path = path.expanduser().resolve()
    errors: list[str] = []
    config_path = project_path / CONFIG_FILE

    if not config_path.is_file():
        errors.append(f"Required file is missing: {CONFIG_FILE}")
    else:
        errors.extend(_validate_config(config_path))

    directories, artifacts = _project_contract(project_path)
    for relative_directory in directories:
        if not (project_path / relative_directory).is_dir():
            errors.append(f"Required directory is missing: {relative_directory}")
    for relative_path in artifacts:
        if not (project_path / relative_path).is_file():
            errors.append(f"Required file is missing: {relative_path}")

    database_path = project_path / DATABASE_RELATIVE_PATH
    if not database_path.is_file():
        errors.append(f"Required file is missing: {DATABASE_RELATIVE_PATH.as_posix()}")
    elif not _is_valid_database(database_path):
        errors.append("Invalid local SQLite index")

    return errors


def _project_contract(project_path: Path) -> tuple[tuple[str, ...], Collection[str]]:
    """Choose the compatible project layout without mutating user-owned files."""
    if (project_path / "career.yml").is_file() or not (
        project_path / "profile.yml"
    ).is_file():
        return PROJECT_DIRECTORIES, PROJECT_ARTIFACTS
    return LEGACY_PROJECT_DIRECTORIES, LEGACY_PROJECT_ARTIFACTS


def _validate_config(config_path: Path) -> list[str]:
    try:
        _read_project_configuration(config_path)
    except (OSError, ValueError, YAMLError, ValidationError) as error:
        return [f"Invalid {CONFIG_FILE}: {error}"]
    return []


def _read_project_configuration(config_path: Path) -> ProjectConfiguration:
    document = YAML(typ="rt").load(config_path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise ValueError(f"{CONFIG_FILE} must contain a mapping")
    return ProjectConfiguration.model_validate(document)


def load_project_configuration(path: Path) -> ProjectConfiguration:
    """Load the strict configuration used by project-scoped commands."""
    return _read_project_configuration(path.expanduser().resolve() / CONFIG_FILE)


def _yaml_string(value: str) -> str:
    """Return a safe double-quoted YAML scalar for generated configuration."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _atomic_write(path: Path, content: str) -> None:
    file_descriptor, temporary_path = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        text=True,
    )
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8", newline="\n") as file:
            file.write(content)
        os.replace(temporary_path, path)
    except BaseException:
        Path(temporary_path).unlink(missing_ok=True)
        raise


def _initialize_database(database_path: Path) -> None:
    with closing(sqlite3.connect(database_path)) as connection:
        with connection:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS schema_migrations (
                    version INTEGER PRIMARY KEY,
                    applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            )
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS project_metadata (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                )
                """
            )
            connection.execute(
                "INSERT OR IGNORE INTO schema_migrations (version) VALUES (1)"
            )


def _database_schema_version(database_path: Path) -> int:
    with closing(
        sqlite3.connect(f"file:{database_path}?mode=ro", uri=True)
    ) as connection:
        row = connection.execute("SELECT MAX(version) FROM schema_migrations").fetchone()
    return int(row[0] or 0)


def _is_valid_database(database_path: Path) -> bool:
    try:
        return _database_schema_version(database_path) >= 1
    except sqlite3.Error:
        return False
